### ISSUE TITLE
[BUG] is this coin dead

### ISSUE THREAD

**Issue by bigmac5753** [VercauterenK/littlelambocoin#1]
is this coin dead?

**Comment by VercauterenK** [comment]
Hi,

Today i am gonna install some timelords and try to finish the explorer didn't know people are already using it.

Will keep you informed.

**Comment by bigmac5753** [comment]
Excellent.  looks like people try to jump on forks as early as possible.  

I can run a timelord for a few days if it'll help.  Do you have plans for a discord server?

**Comment by VercauterenK** [comment]
Launched  2 timelords today gonna launch some other do you use the gui with the logo of llc or do you have an old fork.
Really didn't thought that people would already use it.
If plans go through the coin will be listed on an exchange and will be accepted in many car tuning shops in Belgium.

**Comment by bigmac5753** [comment]
The logo on mine is HDDCoin, I guess I need to update lol

**Comment by VercauterenK** [comment]
Yeah there is also an change in the server.py so there is no conflicts with other coins.
sometimes its not enough to just remove the old one and reinstall sometimes you need to restart the pc.
this should be the logo
https://www.publiproductions.be/llc/logo_big.png

**Comment by bigmac5753** [comment]
yes, have correct fork now.
Do you have plans for discord?  I could set a server up if you want.

**Comment by VercauterenK** [comment]
Yeah i have but not yet first want everything to be good. Don't want it let become another shit fork.

**Comment by VercauterenK** [comment]
Can you keep me informed if you are synced or if there are any problems (my timelords are still syncing added them to the dns) so normally everything should work in a few hours and happy mining.

**Comment by bigmac5753** [comment]
Understood, there's certainly plenty of those around.

Yes, will keep you posted on here.  Are chia plots compatible?

**Comment by VercauterenK** [comment]
> Understood, there's certainly plenty of those around.
> 
> Yes, will keep you posted on here. Are chia plots compatible?

Yes OG plots are compatible

**Comment by bigmac5753** [comment]
I've added plot directories but no plots showing and the refresh plots option is missing from the plots tab.

I was synced to 2,813 but now not synced.

**Comment by VercauterenK** [comment]
Yeah keep it running gonna change some setups at my side now the master is an timelord in my home and want them all at server location. You will start mining when i've done that things.

**Comment by bigmac5753** [comment]
I assume you'll change SSL cert also?

**Comment by VercauterenK** [comment]
> I assume you'll change SSL cert also?

Next problem thanks ;-)

**Comment by bigmac5753** [comment]
As the repo disappeared I stopped the farmer.  Do you want me to continue?

**Comment by VercauterenK** [comment]
> As the repo disappeared I stopped the farmer. Do you want me to continue?

Do you have discord or telegram? Then i will contact you.

**Comment by bigmac5753** [comment]
I'm on discord: bigmac#8002

**Comment by mgrubiak** [comment]
> > As the repo disappeared I stopped the farmer. Do you want me to continue?
> 
> Do you have discord or telegram? Then i will contact you.

you have discord for this project?

**Comment by bigmac5753** [comment]
No, I assumed from the messages above you would set up a server.  would you like me to set one up?

**Comment by mgrubiak** [comment]
You can join this server https://discord.gg/4GntC59Z before creating your own, many people already going for littlelambo on it.

**Comment by bigmac5753** [comment]
ok, joined.  was thinking more of a server specific to this fork like most others have done.  I can set one up and make you admin if you want.

**Comment by VercauterenK** [comment]
Hi All,

The point of this coin is to get some high profile car tuning shops to accept this coin. For the moment i am working on the windows version. The current chain will be the final chain. I have it really busy with some meetings for benelux and france for the tuners.

**Comment by bigmac5753** [comment]
https://discord.gg/c2dHDJsa

**Comment by bigmac5753** [comment]
any updates?

**Comment by bigmac5753** [comment]
I assume this fork is abandoned, discord server will be deleted.
